Lightmatter/django-hydra

project_name/settings/base.py, setup-heroku.sh
=> changing heroku forking to work correctly

requirements.txt
They added a couple nice fields (Zip, SSN, etc.)
=> Bump django-localflavor version

cookiecutter.json, hooks/post_gen_project.sh, hooks/pre_gen_project.sh, {{cookiecutter.repo_name}}/.env, {{cookiecutter.repo_name}}/.env.example, {{cookiecutter.repo_name}}/.gitignore, {{cookiecutter.repo_name}}/requirements-dev.txt, {{cookiecutter.repo_name}}/requirements.txt, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/account/forms.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/account/serializers.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/account/tests.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/account/urls.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/account/views.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/contrib/__init__.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/contrib/sites/__init__.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/contrib/sites/migrations/0001_initial.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/contrib/sites/migrations/0002_set_site_domain_and_name.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/contrib/sites/migrations/__init__.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/base.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/heroku.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/local.py
=> Contrib site migration

{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/util/libsass_compiler.py
* Remove unused finder
* Remove dead commented out code
* Source maps end in .map
=> Update libsass compiler

README.md, {{cookiecutter.repo_name}}/requirements-dev.txt
=> fixing prospector issue 

{{cookiecutter.repo_name}}/README.md, {{cookiecutter.repo_name}}/package.json, {{cookiecutter.repo_name}}/scripts/start.sh
This fixes issues where lint-staged was never running for me as well as updating the actual scripts to be more effective.
=> updating linting

{{cookiecutter.repo_name}}/requirements.txt
Resolves local dev issue on Mac Catalina
=> Bump psycopg2-binary version to 2.8.4

{{cookiecutter.repo_name}}/.eslintrc, {{cookiecutter.repo_name}}/.prettierrc.json, {{cookiecutter.repo_name}}/src/components/AccountPageHeader.jsx, {{cookiecutter.repo_name}}/src/components/Header.jsx, {{cookiecutter.repo_name}}/src/components/PasswordField.jsx, {{cookiecutter.repo_name}}/src/models/user.js, {{cookiecutter.repo_name}}/src/pages/_error.jsx, {{cookiecutter.repo_name}}/src/pages/account/change-email.jsx, {{cookiecutter.repo_name}}/src/pages/account/change-password.jsx, {{cookiecutter.repo_name}}/src/pages/account/delete-account.jsx, {{cookiecutter.repo_name}}/src/pages/account/index.jsx, {{cookiecutter.repo_name}}/src/pages/account/reset/confirm/[uid]/[token].jsx, {{cookiecutter.repo_name}}/src/pages/account/reset/password.jsx, {{cookiecutter.repo_name}}/src/pages/error-page.jsx, {{cookiecutter.repo_name}}/src/pages/login.jsx, {{cookiecutter.repo_name}}/src/pages/signup.jsx, {{cookiecutter.repo_name}}/src/util/axios.js, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/home/views.py
=> Makes menu links clickable always

{{cookiecutter.repo_name}}/src/components/Header.jsx, {{cookiecutter.repo_name}}/src/components/PasswordField.jsx, {{cookiecutter.repo_name}}/src/components/router/Link.jsx, {{cookiecutter.repo_name}}/src/models/user.js, {{cookiecutter.repo_name}}/src/pages/_app.jsx, {{cookiecutter.repo_name}}/src/pages/_document.jsx, {{cookiecutter.repo_name}}/src/pages/_error.jsx, {{cookiecutter.repo_name}}/src/pages/account/change-email.jsx, {{cookiecutter.repo_name}}/src/pages/account/change-password.jsx, {{cookiecutter.repo_name}}/src/pages/account/delete-account.jsx, {{cookiecutter.repo_name}}/src/pages/account/index.jsx, {{cookiecutter.repo_name}}/src/pages/account/reset/confirm/[uid]/[token].jsx, {{cookiecutter.repo_name}}/src/pages/account/reset/password.jsx, {{cookiecutter.repo_name}}/src/pages/error-page.jsx, {{cookiecutter.repo_name}}/src/pages/login.jsx, {{cookiecutter.repo_name}}/src/util/withAuth.jsx, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/urls.py
=> Linting fixes

{{cookiecutter.repo_name}}/docker-compose.yml, {{cookiecutter.repo_name}}/image/runit/nextjs, {{cookiecutter.repo_name}}/package.json, {{cookiecutter.repo_name}}/scripts/setup-heroku.sh, {{cookiecutter.repo_name}}/src/components/Header.jsx, {{cookiecutter.repo_name}}/src/components/footer.jsx, {{cookiecutter.repo_name}}/src/components/header.jsx, {{cookiecutter.repo_name}}/src/components/router/Link.jsx, {{cookiecutter.repo_name}}/src/models/user.js, {{cookiecutter.repo_name}}/src/util/withAuth.jsx, {{cookiecutter.repo_name}}/terraform/modules/aws/main.tf
In setup-heroku.sh:
- Use a loop instead of repeating commands for each environment
- Don't use heroku fork
- Set value of ENVIRONMENT to dev/staging/prod
In terraform config:
- Set username correctly
In nextjs code:
- Fix eslint errors in header and footer
- Format `router/Link.jsx` with eslint
- Enable debugger when running locally
=> Template fixes

{{cookiecutter.repo_name}}/src/pages/[...slug].jsx
`PropTypes.object` should be `null` for the data we default to for Content Page
=> fix: prop types for content page

{{cookiecutter.repo_name}}/jsconfig.json
This helps fix some language-server related issues.
=> Add options to JSConfig.json for language server

{{cookiecutter.repo_name}}/package.json, {{cookiecutter.repo_name}}/postcss.config.js
* Add `postcss-nested` and `sass` npm packages
* Add `postcss-nested` to postcss plugins
* Use `require()` in postcss.config.js
=> [fix] Make scss nesting work with postcss

.gitignore, .vscode/settings.json, {{cookiecutter.repo_name}}/.vscode/extensions.json, {{cookiecutter.repo_name}}/.vscode/launch.json, {{cookiecutter.repo_name}}/.vscode/settings.json, {{cookiecutter.repo_name}}/.vscode/tasks.json
This adds some pretty helpful default settings and launch configurations for VSCode users.
=> Add VSCode helpers

{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/config/settings/base.py
A few crucial settings were removed during the settings update. This fixes those unintended changes.
=> Fix settings

.github/dependabot.yml
Hopefully this will keep both Hydra and template packages up to date. I don't think there's any way to test this without merging it in and seeing if it works.
=> Add project-level dependabot config

.github/workflows/project_ci.yml
Note: I also added a branch protection rule that requires tests to pass before merging is allowed.
=> Auto-approve and merge dependabot PRs

{{cookiecutter.repo_name}}/poetry.lock, {{cookiecutter.repo_name}}/pyproject.toml, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/config/settings/base.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/config/urls.py, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/user/models.py
The default settings + the admin integration seem sensible enough.
Works pretty well as far as I tested.
=> Add django-hijack

README.md
Just removed 1 line but my editor went to town on formatting, lmk if you want me to remove formatting changes
=> removing reference to 3.0 in template

{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/account/signup.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/components/button.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/components/util.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/input.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/label.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/password.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/select.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/index.jinja
This allows implementers to pass a dictionary of attributes to the button component.
=> Add button attributes

{{cookiecutter.repo_name}}/gunicorn.conf.py
You can test locally by running `gunicorn`.
=> Add gunicorn configuration

{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/django/forms/widgets/radio.html, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/field.jinja, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/forms/radio.jinja
The code is pretty ugly. Hopefully necessarily so. It could also probably use more styling to say the least.
=> Add radio widget

{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/templates/components/button.jinja
This will conflict with https://github.com/Lightmatter/django-hydra/pull/278 so I can rebase whenever we decide to merge that.
=> adding ability for button to be a link

scripts/mac_intel_install.sh
I setup a new mac recently, I had to setup a new mac and ran into some issues. Particularly with Pyenv + yarn being installed, for whatever reason that messed up the package.json file of the project I installed in the dir of.
=> Fix up fresh machine script

{{cookiecutter.repo_name}}/.eslintrc.js, {{cookiecutter.repo_name}}/package-lock.json, {{cookiecutter.repo_name}}/package.json, {{cookiecutter.repo_name}}/tsconfig.json, {{cookiecutter.repo_name}}/vitest.config.ts, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/links.ts, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/test/links.test.ts, {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static_source/js/test/main.test.ts
Add tests for links.ts and an example test to run code in vite hmr.
=> Add vitest
